// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// NOTE:
// Lovable projects should NOT depend on Vite env vars (VITE_*) at runtime.
// Use the project ref URL + anon key directly.
const SUPABASE_URL = 'https://zjobnxbzdtqsgbfdxzqo.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqb2JueGJ6ZHRxc2diZmR4enFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxODE4NTgsImV4cCI6MjA3OTc1Nzg1OH0.zaHZQWnwxoGmmVm2OFP5ynN3cZ6G8iIsm0ydyzCp7NU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});